# Search query
query: "santa cruz"

# Cities/Regions to query
cities:
- eauclaire

min_price: 100
max_price: 5000

# NOT case sensitive - Checks titles for these key words (frame size?)
titlekeywords:
 - chamelon

# NOT case sensitive - Checks bodies for these key words
bodykeywords:
 - brakes

# NOT case sensitive - Checks attributes for these frame sizes
framesizes:
- S
- Small
- Large

min_frame:
max_frame: