# Search query
query: "stumpjumper"

# Cities/Regions to query
cities:
- eauclaire
- denver
- portland

min_price: 1200
max_price: 2000

# NOT case sensitive - Checks titles for these key words (frame size?)
titlekeywords:


# NOT case sensitive - Checks bodies for these key words
bodykeywords:


# NOT case sensitive - Checks attributes for these frame sizes
framesizes:
 - Small
 - S

min_frame: 15
max_frame: 16.5